@startuml
!theme cerulean
left to right direction

actor Usuário
agent Objeto
database database
frame JPClasse
agent ClasseDAO 

Usuário --> JPClasse : 1.listenerCadastrar()
JPClasse --> Objeto : 2.Objeto()
JPClasse --> ClasseDAO : 3.ClasseDAO()
ClasseDAO --> database : 4.cadastrarObjeto()
JPClasse --> JPClasse : 5.Listar()

@enduml