@startuml
!theme cerulean
start
repeat
	if (Voltar?) then (sim)
		stop
	else (não)
		repeat
			:Preencher campos;
		repeat while (Cadastrar?) is (não) not (sim)
	endif
        :Instancia novo Objeto;
	:Instancia Classe DAO;
	:Cadastra no Banco;
repeat while
@enduml