@startuml
!theme cerulean
start
repeat
	if (Voltar?) then (sim)
		stop
	else (não)
		repeat
			:Seleciona: Tipo, Pesquisa e Ordem;
		repeat while (Pesquisar?) is (não) not (sim)
	endif
	:Pesquisa no banco;
	:Monta tabela;
repeat while
@enduml