@startuml
!theme blueprint
left to right direction

actor "Administrador" as Admin
actor "Usuário" as User

rectangle SHM {
	Admin -up- (Manter Usuário)
	Admin -up- (Manter Cliente)
	Admin -up- (Manter Produto)
	Admin -up- (Manter Venda)
	Admin -up- (Histórico)
	(Histórico) <.right. (Previsão) : extends

	User -- (Manter Cliente)
	User -- (Manter Produto)
	User -- (Manter Venda)
	User -- (Histórico)
}
@enduml